### ISSUE TITLE
TestModuleFor{App,Acceptance} proposal

### ISSUE THREAD

**Issue by seanpdoyle** [switchfly/ember-test-helpers#94]
WRT https://github.com/rwjblue/ember-qunit/pull/71

@rwjblue @stefanpenner I'm looking into baking this into [switchfly/ember-test-helpers](https://github.com/switchfly/ember-test-helpers):

```js
// tests/helpers/module-for-acceptance.js

import Ember from 'ember';
import { module } from 'qunit';
import startApp from './start-app'; // This file is the unchanged, `ember new` version

export default function(name, options = {}) {
  let application;

  module(`Acceptance | ${name}`, {
    beforeEach: function() {
      application = startApp();
      if (options.beforeEach) {
        options.beforeEach.call(this, arguments);
      }
    },

    afterEach: function() {
      Ember.run(application, 'destroy');
      if (options.afterEach) {
        options.afterEach.call(this, arguments);
      }
    }
  });
}
```

So that it's integration with ember-qunit would be as minimal as the rest.

I'm having trouble figuring out how, though.

Any ideas?

Will this work at all, or is it best left as a hand-rolled helper?

**Comment by rwjblue** [comment]
I guess I don't understand what you mean.

**Comment by rwjblue** [comment]
Since we don't really need any special shenanigans to deal with bizarreness in Ember, this sort of thing likely lives in ember-qunit itself.

**Comment by seanpdoyle** [comment]
Sorry if this is too cryptic.

https://github.com/rwjblue/ember-qunit/pull/71 introduces a `moduleForApp` to wrap 

https://github.com/ember-cli/ember-cli/blob/8d9c3a4579abb65416f40ec0dd46008b3c159a49/blueprints/acceptance-test/files/tests/acceptance/__name__-test.js#L3-L13

I'd like to push that forward, but it looks like that PR predates the `ember-test-helpers` / `ember-qunit` split, so I tried to work it into this repo instead but I hit a wall.

**Comment by cowboyd** [comment]
We've been toying around with implementing something like this for use in one of our addons. Thus far, we've been writing all the code inside the addon, but with an eye for potentially extracting it out for inclusion into `ember-test-helpers`

https://gist.github.com/Robdel12/c8470434a5e0ded666db

It's been working really well thus far, but my primary concern is with these lines here https://gist.github.com/Robdel12/c8470434a5e0ded666db#file-test-helper-js-L2-L3

Since this class is embedded into our addon, it has access to the (dummy) application's class and config, but is that going to pose a problem if this code were to live in `ember-test-helpers`? 

Also, the `startApp()` test helper that gets generated by `ember-mocha` and `ember-qunit` acceptance-test blueprints allows passing one-off options to `Application.create()` per test. Changing settings suite-wide in environment.js for `'test'` has always been sufficient for us, so we wouldn't miss that, but it might be a problem for others.

**Comment by cowboyd** [comment]
Unless anybody sees anything obviously flawed with this approach, we'll go ahead and submit the PR.

**Comment by seanpdoyle** [comment]
@cowboyd I say go ahead, I have an [outstanding PR to ember-cli/ember-cli](https://github.com/ember-cli/ember-cli/pull/4692), but I'm having some trouble with it.

If we could get something working in this repo instead, I think we'd be better off.

**Comment by seanpdoyle** [comment]
Added to `ember-cli` directly in https://github.com/ember-cli/ember-cli/pull/4692
